### ISSUE TITLE
Issue with the unzip module

### ISSUE THREAD

**Issue by missinglink** [pelias/geonames#1]
The module used to do a streaming unzip (called `unzip` in `npm`) seems to crash with a fatal error when it finds an "invalid signature".

At time of writing this prevented importing any more than 4,895,000 records from the 'allCountries.zip' file.

Ideally the library will just skip over erroneous records with an error provided via `stderr`.

We can either patch the `unzip` module, or wait for the `geonames` data to be fixed.

```bash
writing 1000 records to ES { written: 5160000, inserted: 4892000, queued: 268000 }
writing 1000 records to ES { written: 5161000, inserted: 4894000, queued: 267000 }
writing 1000 records to ES { written: 5162000, inserted: 4895000, queued: 267000 }

Error: invalid signature: 0xcb633d21
    at /var/www/pelias-geonames/node_modules/unzip/lib/parse.js:63:13
    at process._tickCallback (node.js:419:13)
```

**Comment by sevko** [comment]
@hkrishna runs the import frequently (I think). Have you seen this error lately?

**Comment by hkrishna** [comment]
No, I haven't seen this error as of 3 days ago when I imported allCountries
