### ISSUE TITLE
What about alternateNames.zip?

### ISSUE THREAD

**Issue by sheerun** [pelias/geonames#106]
The alternateNames.zip from http://download.geonames.org/export/dump/ contains a lot lot of alternative names for geonames objects. It could potantially greatly improve search results. Is there a plan to support it?

**Comment by sheerun** [comment]
I'm not 100% sure if allCountries doesn't include all entries from altenateNames.zip (or only some)

**Comment by sheerun** [comment]
I seems so. Also, geonames-stream outputs alternate names as well:
https://github.com/geopipes/geonames-stream/blob/master/lib/alternative_names.js

**Comment by trescube** [comment]
We're in the process of transitioning to [Who's on First](https://whosonfirst.mapzen.com/) (WOF) as our sole gazetteer so while we technically support geonames, there is no active maintenance plan for it other than bug fixes.  Loosely speaking, WOF is an aggregator of data sources with editorial content of our own.  One of those data sources is geonames and we use it's fields when appropriate so we'll most likely always have some geonames support, it just won't be a separable data source.

**Comment by sheerun** [comment]
OK, then. I think there's a bug in indexing. If I use `setName` multiple times (with different key), pelias api won't return results for alternate names. For example "Breslau" is german name for "Wrocław" city of Poland.

**Comment by sheerun** [comment]
I filled issue at: https://github.com/pelias/api/issues/610
