### ISSUE TITLE
Can't install pelias-geonames or it's dependencies from npm

### ISSUE THREAD

**Issue by eugenezinoviev** [pelias/geonames#184]
Can't install pelias-geonames or it's dependencies from npm on Windows.
Post-install tries to create folder metadata which already exists (see npm logs attached).
Can you use mkdirp package instead of "mkdir -p" command?

[npm-debug.txt](https://github.com/pelias/geonames/files/893182/npm-debug.txt)

**Comment by missinglink** [comment]
yes! we'd be happy to accept a PR for this

**Comment by eugenezinoviev** [comment]
https://github.com/pelias/geonames/pull/185
