### ISSUE TITLE
Create mapping from Geonames feature codes to layers

### ISSUE THREAD

**Issue by orangejulius** [pelias/geonames#31]
All Geonames records currently have layer `venue`, which is not very helpful or accurate most of the time. Fortunately there is a great set of [feature codes](http://www.geonames.org/export/codes.html) that can easily be mapped to most of our existing layers, and possibly new ones if we so desired.

The most important is definitely admin levels.

**Comment by missinglink** [comment]
related: https://github.com/pelias/geonames/issues/20
related: https://github.com/pelias/geonames/pull/22

see: https://github.com/pelias/geonames/blob/master/metadata/category_mapping.json
