### ISSUE TITLE
error: [dbclient] invalid resp from es bulk index operation

### ISSUE THREAD

**Issue by sankeykool** [pelias/geonames#33]
Getting this error while ./bin/pelias-geonames -i all

**Comment by missinglink** [comment]
hi @sankeykool what version of elasticsearch are you running?

**Comment by sankeykool** [comment]
1.7.1

**Comment by missinglink** [comment]
that version is correct. I just pulled the latest version and it's working for me on `1.7.2`.

could you provide more info:
- is this the first time you've run pelias, or is this an intermittent error?
- can you provide the full output log?

**Comment by missinglink** [comment]
it may be a configuration issue, have a look at the docs here https://github.com/pelias/openstreetmap and see if something looks out of place.

**Comment by orangejulius** [comment]
Hey @sankeykool,
In the last couple days we've pushed a bunch of different updates to this importer that should improve its stability across different systems. Can you try again using the latests master, and tell me which version of Nodejs you're using? Thanks

**Comment by orangejulius** [comment]
Closing this issue because, as mentioned, I think we've solved this sort of issue with some of the various improvements to the importer. If not, feel free to re-open.
