### ISSUE TITLE
dl dir doesnt exist and isnt created

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/geonames#357]
wof downloader for instance creates the download dir, here its not being created.

```
jeremyr@w6:~/pelias_metal/geonames$ npm run download 

> pelias-geonames@0.0.0-development download /home/jeremyr/pelias_metal/geonames
> ./bin/download


2019-04-10T15:22:00.186Z - info: [geonames] downloading datafile from: http://download.geonames.org/export/dump/allCountries.zip
/bin/sh: 1: cannot create /mnt/data_science/pelias_w6/data/geonames/allCountries.zip: Directory nonexistent
Geonames download finished with exit code 2
```

**Comment by orangejulius** [comment]
Hey, thanks for reporting this. I actually noticed it a few days before you mentioned it in the pelias/docker issue. The geonames Dockerfile was written a long time ago when we had no idea what we were doing. Fortunately the geonames importer also supports a streaming download, so there's no impact on builds.

In the long run we should fix this by creating that directory if it doesn't exist, exactly like the other importers do. However this is extremely low priority.
