### ISSUE TITLE
Region (RGN) records are shown as venues

### ISSUE THREAD

**Issue by missinglink** [pelias/geonames#70]
region records like this should be removed:

``` javascript
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.90039,
          61.68987
        ]
      },
      "properties": {
        "id": "7729883",
        "gid": "geonames:venue:7729883",
        "layer": "venue",
        "source": "geonames",
        "name": "Northern Europe",
        "confidence": 0.662,
        "label": "Northern Europe, "
      }
    }
```

**Comment by orangejulius** [comment]
Just found [this London record](http://www.geonames.org/11591955/london.html) (which has a polyogn, fancy!) in some results, and it is also showing up as a venue.

**Comment by orangejulius** [comment]
Looking at this a bit further (and clearly @Joxit is as well), `RGN` records in Geonames are very strange. Clearly they often don't map to anything in the WOF hierarchy very well.

**Comment by orangejulius** [comment]
Another example: [Southern California](http://www.geonames.org/11071615/southern-california.html#) is marked as `L RGN`.

**Comment by orangejulius** [comment]
@Joxit you mentioned in a commit comment that `RGN` geonames records are important in france. Can you give some examples that are useful? I'm wondering if we could consider blocking all `RGN` Geonames records, since the mapping really doesn't seem straightforward.

**Comment by Joxit** [comment]
Comment from #338 ?
No, `RGN` geonames records looks like a spaghetti dish for France. That is why I removed them with #338. All real regions are in `ADM1` records :smile:.

It's totally safe for France to remove `RGN` records :wink:

**Comment by orangejulius** [comment]
Oh, great! In that case I might just remove them generally as well. I have skimmed through the full list of them and didn't see any we can't live without.
